  version: "3.8"

  services:
    backend:
      build: ./backend
      networks:
        - app-network
      depends_on:
        - database
      ports:
        - "8081:8080"

    database:
      build: ./db
      networks:
        - app-network
      environment:
        POSTGRES_DB: db
        POSTGRES_USER: usr
        POSTGRES_PASSWORD: pwd
      volumes:
        - pgdata:/var/lib/postgresql/data

    httpd:
      build: ./proxy
      ports:
        - "8082:80"
      networks:
        - app-network
      depends_on:
        - backend

  networks:
    app-network:

  volumes:
    pgdata:
